# Netlify configuration for Apple Pay domain verification
[[headers]]
  for = "/.well-known/apple-developer-merchantid-domain-association"
  [headers.values]
  Content-Type = "application/octet-stream"
